{
 "title": "Kuma Mesh",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mesh",
    "label": "Mesh",
    "query": "label_values(envoy_server_live, mesh)"
   }
  ]
 },
 "panels": [
  { "title": "Dataplanes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dataplanes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(envoy_server_live{mesh=\"$mesh\"}) - sum(envoy_server_live{mesh=\"$mesh\"})",
     "legendFormat": "Off"
    },
    {
     "expr": "sum(envoy_server_live{mesh=\"$mesh\"})",
     "legendFormat": "Live"
    }
   ]
  },
  {
   "title": "Dataplanes connected to the Control Plane",
   "type": "graph",
   "description": "Note that if Control Plane does not sent FIN segment, Dataplanes can still think that connection is up waiting for new update even that Control Plane is down.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(envoy_server_live{mesh=\"$mesh\"}) - sum(envoy_cluster_upstream_cx_active{envoy_cluster_name=\"ads_cluster\",mesh=\"$mesh\"})",
     "legendFormat": "Disconnected"
    },
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{envoy_cluster_name=\"ads_cluster\",mesh=\"$mesh\"})",
     "legendFormat": "Connected"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Bytes flowing through Envoy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_tx_bytes_total{mesh=\"$mesh\"}[1m]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_rx_bytes_total{mesh=\"$mesh\"}[1m]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Connection/Requests errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_connect_timeout{mesh=\"$mesh\"}[1m]))",
     "legendFormat": "Connection timeout"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_pending_failure_eject{mesh=\"$mesh\"}[1m]))",
     "legendFormat": "Pending failure ejection"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_pending_overflow{mesh=\"$mesh\"}[1m]))",
     "legendFormat": "Pending overflow"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_timeout{mesh=\"$mesh\"}[1m]))",
     "legendFormat": "Request timeout"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_rx_reset{mesh=\"$mesh\"}[1m]))",
     "legendFormat": "Response reset"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_tx_reset{mesh=\"$mesh\"}[1m]))",
     "legendFormat": "Request reset"
    }
   ]
  },
  { "title": "Health Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active Health Checks",
   "type": "graph",
   "description": "Data is only available if HealthCheck policy is applied.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((sum(rate(envoy_cluster_health_check_success{mesh=\"$mesh\"}[1m])) / sum(rate(envoy_cluster_health_check_attempt{mesh=\"$mesh\"}[1m]))))",
     "legendFormat": "Success rate"
    }
   ]
  },
  {
   "title": "Passive Health Checks",
   "type": "graph",
   "description": "Data is only available if HealthCheck policy is applied. Note that passive health checks are executed on healthy instances marked by active health checks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(envoy_cluster_outlier_detection_ejections_active{mesh=\"$mesh\"}) / sum(envoy_cluster_membership_total{mesh=\"$mesh\"})",
     "legendFormat": "Success rate"
    }
   ]
  }
 ]
}