{
 "title": "Kuma L4",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dataplane",
    "label": "dataplane",
    "query": "label_values(envoy_server_live, dataplane)"
   },
   {
    "name": "mesh",
    "query": "label_values(envoy_server_live, mesh)"
   }
  ]
 },
 "panels": [
  { "title": "Dataplane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "envoy_server_live{dataplane=\"$dataplane\",mesh=\"$mesh\"}"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "envoy_server_memory_allocated{dataplane=\"$dataplane\",mesh=\"$mesh\"}"
    }
   ]
  },
  {
   "title": "Active connections to the Control Plane",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_total{envoy_cluster_name=\"ads_cluster\",dataplane=\"$dataplane\",mesh=\"$mesh\"}",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  { "title": "Incoming traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Active Connections to this Dataplane",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_total{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name=~\"localhost.*\"}[5m])",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Bytes received from requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_tx_bytes_total{dataplane=\"$dataplane\",envoy_cluster_name=~\"localhost.*\",mesh=\"$mesh\"}[5m])",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Bytes sent in responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{dataplane=\"$dataplane\",envoy_cluster_name=~\"localhost.*\",mesh=\"$mesh\"}[5m])",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  { "title": "Outgoing traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active Connections to other Dataplanes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_total{dataplane=\"$dataplane\",mesh=\"$mesh\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\"}[5m])",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Bytes received from other dataplanes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{dataplane=\"$dataplane\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\",mesh=\"$mesh\"}[5m])",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Bytes sent to other dataplanes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_tx_bytes_total{dataplane=\"$dataplane\",envoy_cluster_name!~\"(localhost.*)|ads_cluster|kuma_envoy_admin|access_log_sink\",mesh=\"$mesh\"}[5m])",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  }
 ]
}