#!/bin/sh
KUMA_MODE=zone \
KUMA_DP_SERVER_PORT=25678 \
KUMA_DIAGNOSTICS_SERVER_PORT=25680 \
KUMA_MONITORING_ASSIGNMENT_SERVER_PORT=25676 \
KUMA_API_SERVER_HTTP_PORT=25681 \
KUMA_API_SERVER_HTTPS_ENABLED=false \
KUMA_DNS_SERVER_PORT=25653 \
KUMA_MULTIZONE_ZONE_NAME="cluster-2" \
KUMA_MULTIZONE_ZONE_GLOBAL_ADDRESS="grpcs://localhost:35685" \
kuma-cp run
