# -*- mode: ruby -*-
# vi: set ft=ruby :

# Control-plane IP
kuma_cp_ip= "192.168.33.10"

boxes = [
  {
    name: "kuma-cp",
    ip: "#{kuma_cp_ip}",
    box: "ubuntu/xenial64",
    script: [
      "./control-plane/bootstrap.sh"
    ]
  },
  {
    name: "frontend",
    ip: "192.168.33.20",
    box: "ubuntu/xenial64",
    file: "app",
    script: [
      "./frontend/bootstrap.sh",
      "./frontend/dataplane.sh"
    ]
  },
  {
    name: "backend",
    ip: "192.168.33.30",
    box: "ubuntu/xenial64",
    file: "api",
    script: [
      "./backend/bootstrap.sh",
      "./backend/dataplane.sh"
    ]
  },
  {
    name: "elastic",
    ip: "192.168.33.40",
    box: "elastic/ubuntu-16.04-x86_64",
    script: [
      "./elastic/bootstrap.sh",
      "./elastic/dataplane.sh"
    ]
  },
  {
    name: "redis",
    ip: "192.168.33.50",
    box: "ubuntu/xenial64",
    script: [
      "./redis/bootstrap.sh"
      # "./redis/dataplane.sh"            # <-- Not automating dataplane deployment so people can DIY
    ]
  }
]

Vagrant.configure("2") do |config|

  config.vm.synced_folder "./", "/home/vagrant/kuma"

  boxes.each do |box|
    
    config.vm.define box[:name] do |srv|
      srv.vm.box = box[:box]
      srv.vm.hostname = box[:name]
      srv.vm.network :private_network, ip: box[:ip]
      if box[:name] == "frontend"
        # So we can access the frontend application when mTLS is turned on
        srv.vm.network "forwarded_port", guest: 8080, host: 8080, guest_ip: "127.0.0.1"
      end

      if box[:file]
        srv.vm.provision "file", source: "../#{box[:file]}", destination: "$HOME/#{box[:file]}"
      end
      
      box[:script].each do |script|
        srv.vm.provision :shell, path: script
      end 
  
    end

  end

end
