#!/bin/sh
KUMA_MODE=remote \
KUMA_DP_SERVER_PORT=15678 \
KUMA_XDS_SERVER_DIAGNOSTICS_PORT=15680 \
KUMA_MONITORING_ASSIGNMENT_SERVER_GRPC_PORT=15676 \
KUMA_API_SERVER_HTTP_PORT=15681 \
KUMA_API_SERVER_HTTPS_ENABLED=false \
KUMA_DNS_SERVER_PORT=15653 \
KUMA_MULTICLUSTER_REMOTE_ZONE="cluster-1" \
KUMA_MULTICLUSTER_REMOTE_GLOBAL_ADDRESS="grpcs://localhost:35685" \
kuma-cp run
