#!/bin/sh
KUMA_MODE=global \
KUMA_XDS_SERVER_DIAGNOSTICS_PORT=35680 \
KUMA_MONITORING_ASSIGNMENT_SERVER_GRPC_PORT=35676 \
KUMA_API_SERVER_HTTP_PORT=5681 \
KUMA_API_SERVER_HTTPS_ENABLED=false \
KUMA_DNS_SERVER_PORT=35653 \
KUMA_MULTICLUSTER_GLOBAL_KDS_GRPC_PORT=35685 \
kuma-cp run
